server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: academic-management-system

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academic_management_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 10s 

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*.xml

# JWT配置
jwt:
  secret: academic-management-system-secret-key-2024-very-long-and-secure-key-for-hs512-algorithm-must-be-at-least-512-bits-long-this-is-a-very-long-secret-key-that-meets-the-requirements
  expiration: 86400000 # 24小时，单位毫秒

# 文件上传配置
file:
  upload:
    path: E:/Project/file
    max-size: 10MB
    allowed-types: pdf,doc,docx,jpg,jpeg,png

# 日志配置
logging:
  level:
    com.academic: debug
    org.springframework.security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
